import type { LanguageCode } from "./types";

type BookletText = {
  chapters: string[];
  sectionLabels: string[];
  cover: [string, string, string, string];
  nav: [string, string, string, string];
  welcome: { title: string; paragraphs: [string, string, string]; picture: string; alt: string };
  arrival: { title: string; parking: string; intro: string; reminderLabel: string; reminder: string; planButton: string; planAlt: string; planCaption: string; planTitle: string; planVersion: string; planOpen: string; planClose: string };
  contacts: { title: string; roles: string[]; emailTitle: string };
  hours: { title: string; limits: string; weekdays: string; saturday: string; breakTitle: string; rules: string[]; apples: string };
  hygiene: { title: string; imageAlt: string; rules: string[]; washLead: string; washSoon: string; handsTitle: string; hands: string; linkClothes: string; linkHands: string };
  safety: { title: string; imageAlt: string; rules: string[]; emergencyTitle: string; alert: string; evacuation: string; linkSafety: string; linkEmergency: string };
  packing: { title: string; rules: string[]; motto: string; link: string };
  environment: { title: string; items: { title: string; text: string }[] };
  team: { title: string; imageAlt: string; picture: string; intro: string; rightsTitle: string; rights: string; duties: string };
  ideas: { title: string; anonymous: string; paper: string; emailTitle: string; email: string; emailWarning: string; urgent: string; emailSubject: string };
  next: { label: string; title: string; intro: string; button: string };
};

export const bookletText: Record<LanguageCode, BookletText> = {
  FR: {
    chapters: ["Bienvenue", "Votre arrivée", "Vos contacts", "Horaires & pauses", "Tenue & hygiène", "Sécurité", "À l’emballage", "Environnement", "Vie d’équipe", "Boîte à idées"],
    sectionLabels: ["NOTRE ENTREPRISE", "VOTRE PREMIER JOUR", "LES PERSONNES À CONNAÎTRE", "ORGANISER SA JOURNÉE", "HYGIÈNE AU QUOTIDIEN", "SE PROTÉGER ET PROTÉGER LES AUTRES", "LE SOIN APPORTÉ AU FRUIT", "PRÉSERVER NOS RESSOURCES", "BIEN VIVRE ENSEMBLE", "VOTRE AVIS COMPTE"],
    cover: ["POMEMBAL · VOTRE LIVRET D’ACCUEIL", "Bienvenue dans l’équipe.", "Les personnes, les lieux et les gestes qui vous accompagnent dès le premier jour.", "Imprimer le livret"],
    nav: ["VOS REPÈRES", "Sommaire du livret", "Urgence", "Haut du livret"],
    welcome: { title: "La qualité commence avec chacun de nous.", paragraphs: ["Pomembal conditionne des pommes destinées à des clients en France et à l’étranger. Du verger à l’emballage, le soin apporté au fruit guide notre travail.", "Respect des personnes, qualité des produits et attention à l’environnement font partie de nos engagements. Votre arrivée est l’occasion de découvrir nos métiers et de prendre vos repères avec l’équipe.", "Une question ? Demandez à votre responsable. Vous êtes accompagné dans la découverte de votre poste."], picture: "Du verger à la station.", alt: "Photographie au verger issue du livret d’accueil" },
    arrival: { title: "Prendre vos repères.", parking: "47300 Bias · Un espace est réservé au stationnement.", intro: "À votre arrivée, présentez-vous au responsable indiqué. Faites-vous montrer votre poste, les vestiaires, la salle de pause, les cheminements et le point de rassemblement.", reminderLabel: "Avant de commencer :", reminder: "identifiez votre responsable, vos horaires et votre poste, les vestiaires, la tenue demandée et les consignes d’urgence.", planButton: "Agrandir le plan", planAlt: "Plan de la station : entrée, bureaux, chambres froides, réfectoire et sanitaires", planCaption: "Plan présent dans le livret d’origine — DOC 24, V1 du 15/11/2023. Suivez les affichages et les consignes sur place.", planTitle: "Plan de la station", planVersion: "DOC 24 · V1 du 15/11/2023 — plan du livret d’origine", planOpen: "Ouvrir l’image dans un nouvel onglet", planClose: "Fermer le plan" },
    contacts: { title: "Qui peut vous aider ?", roles: ["Direction", "Responsable de station et sécurité", "Responsable verger", "Comptabilité", "Sauveteur secouriste du travail", "Responsable qualité et emballage"], emailTitle: "Contacter la direction" },
    hours: { title: "Horaires et pauses.", limits: "Les plages ci-dessous sont les amplitudes maximales possibles. Elles ne représentent pas un horaire de travail systématique : suivez le planning communiqué par l’encadrement.", weekdays: "Lundi au vendredi", saturday: "Samedi", breakTitle: "En salle de repos", rules: ["Retirez votre blouse avant d’entrer.", "Nettoyez votre place et les équipements après utilisation.", "Remettez votre blouse et lavez-vous les mains avant la reprise."], apples: "Des pommes sont à votre disposition pendant les pauses. Vos retours sur leur goût, leur texture et leur qualité sont les bienvenus." },
    hygiene: { title: "Une tenue propre. Les bons gestes.", imageAlt: "Tenue de travail propre avec cheveux couverts", rules: ["Blouse propre, complète et fermée.", "Cheveux entièrement couverts par une charlotte.", "Chaussures propres, fermées et adaptées au poste.", "Ongles courts, sans vernis ni faux ongles.", "Aucun bijou, sauf une alliance simple ; aucune montre ni bracelet.", "Pas de piercing apparent. Évitez maquillage excessif et parfums trop marqués.", "Téléphone et effets personnels rangés dans l’espace prévu."], washLead: "Blouse lavée au minimum une fois par semaine.", washSoon: "Lavez-la plus rapidement si elle est sale ou souillée.", handsTitle: "Le lavage des mains", hands: "Lavez-vous les mains à l’entrée en production, à chaque reprise et avant tout contact avec les fruits. Renouvelez le lavage après les toilettes, un mouchage ou un contact avec des déchets.", linkClothes: "Revoir les règles de tenue", linkHands: "Apprendre le lavage des mains" },
    safety: { title: "La sécurité au poste.", imageAlt: "Illustration des règles de circulation dans la station", rules: ["Respectez les cheminements piétons et les marquages au sol.", "Ne traversez jamais la trajectoire d’un engin.", "Ne retirez aucune protection de machine.", "En cas de blocage, arrêtez votre action et prévenez un responsable.", "Signalez immédiatement un incident ou une situation dangereuse."], emergencyTitle: "En cas d’urgence", alert: "Alertez le responsable ou Dina, sauveteur secouriste du travail. Pour joindre les secours :", evacuation: "À l’alarme, évacuez immédiatement, sans récupérer vos affaires, vers le point de rassemblement au parking visiteurs.", linkSafety: "Revoir la sécurité en station", linkEmergency: "Connaître les gestes d’alerte" },
    packing: { title: "À l’emballage, chaque geste compte.", rules: ["Manipulez les fruits avec soin et respectez les consignes de tri.", "Utilisez uniquement le matériel fourni par Pomembal.", "Ne remettez jamais dans le circuit un fruit tombé au sol.", "Signalez un emballage sale, un objet perdu ou cassé, du verre, du plastique dur ou un corps étranger.", "Prévenez le responsable en cas d’erreur d’étiquette, de variété, de calibre ou d’emballage."], motto: "Je vois. J’agis si je peux le faire sans danger. J’alerte.", link: "Revoir les bons gestes avec les fruits" },
    environment: { title: "Les gestes utiles, tous les jours.", items: [{ title: "Trier", text: "Séparez cartons, déchets organiques et autres déchets selon les consignes de la station." }, { title: "Économiser", text: "Éteignez les lumières inutilisées et fermez les robinets après usage." }, { title: "Signaler", text: "Prévenez le responsable si vous constatez un gaspillage, une fuite ou un dysfonctionnement." }] },
    team: { title: "Une place dans l’équipe.", imageAlt: "L’équipe réunie, photo du livret d’accueil", picture: "Un moment partagé par l’équipe Pomembal.", intro: "Respect, éthique et égalité professionnelle font partie de la vie dans l’entreprise. Les moments conviviaux et les événements internes sont aussi l’occasion de mieux se connaître.", rightsTitle: "Vos droits et vos devoirs", rights: "Le livret rappelle les congés payés, la formation et l’égalité professionnelle. Pour connaître les modalités qui s’appliquent à votre situation, adressez-vous à l’encadrement.", duties: "Respectez les consignes internes, vos collègues et la confidentialité des informations de l’entreprise. Si vous rencontrez une difficulté, parlez-en à votre responsable." },
    ideas: { title: "Une idée peut faire avancer les choses.", anonymous: "Dans la salle de pause, la boîte à idées vous permet de proposer une amélioration ou de signaler une difficulté, de manière anonyme.", paper: "Organisation, sécurité, qualité, environnement ou vie d’équipe : chaque suggestion peut améliorer notre quotidien. Écrivez simplement votre idée sur une feuille, sans indiquer votre nom, puis déposez-la dans la boîte.", emailTitle: "Vous préférez écrire ?", email: "Vous pouvez envoyer un courriel à la direction.", emailWarning: "Attention : un courriel n’est pas anonyme.", urgent: "Pour une situation urgente ou dangereuse, alertez immédiatement un responsable.", emailSubject: "Suggestion pour Pomembal" },
    next: { label: "LA SUITE DE VOTRE PARCOURS", title: "Place aux bons réflexes.", intro: "Retrouvez les huit thèmes de la formation Hygiène et Sécurité, puis testez vos connaissances avec le quiz.", button: "Ouvrir la formation" },
  },
  PL: {
    chapters: ["Witamy", "Pierwszy dzień", "Kontakty", "Godziny i przerwy", "Odzież i higiena", "Bezpieczeństwo", "Pakowanie", "Środowisko", "Praca w zespole", "Skrzynka pomysłów"],
    sectionLabels: ["NASZA FIRMA", "TWÓJ PIERWSZY DZIEŃ", "OSOBY KONTAKTOWE", "ORGANIZACJA DNIA", "CODZIENNA HIGIENA", "BEZPIECZEŃSTWO TWOJE I INNYCH", "DBAŁOŚĆ O OWOCE", "OSZCZĘDZANIE ZASOBÓW", "WSPÓŁPRACA", "TWOJA OPINIA MA ZNACZENIE"],
    cover: ["POMEMBAL · PRZEWODNIK POWITALNY", "Witamy w zespole.", "Poznaj ludzi, miejsca i zasady, które pomogą Ci od pierwszego dnia.", "Drukuj przewodnik"],
    nav: ["NAJWAŻNIEJSZE INFORMACJE", "Spis treści przewodnika", "Numer alarmowy", "Na początek"],
    welcome: { title: "Jakość zaczyna się od każdego z nas.", paragraphs: ["Pomembal pakuje jabłka dla klientów we Francji i za granicą. Troska o owoce towarzyszy nam od sadu aż po pakowanie.", "Szacunek dla ludzi, jakość produktów i troska o środowisko są częścią naszych zobowiązań. Poznaj naszą pracę i zespół, z którym będziesz pracować.", "Masz pytanie? Zapytaj swojego przełożonego. Pomożemy Ci poznać stanowisko pracy."], picture: "Od sadu do pakowni.", alt: "Zdjęcie sadu z oryginalnego przewodnika" },
    arrival: { title: "Poznaj miejsce pracy.", parking: "47300 Bias · Wyznaczono miejsce parkingowe.", intro: "Po przybyciu zgłoś się do wskazanej osoby odpowiedzialnej. Poproś o pokazanie stanowiska pracy, szatni, pokoju przerw, dróg poruszania się i miejsca zbiórki.", reminderLabel: "Przed rozpoczęciem pracy:", reminder: "ustal, kto jest Twoim przełożonym, jakie masz godziny i stanowisko pracy, gdzie są szatnie, jakiej odzieży potrzebujesz i jakie są zasady postępowania w nagłych wypadkach.", planButton: "Powiększ plan", planAlt: "Plan zakładu: wejście, biura, chłodnie, stołówka i sanitariaty", planCaption: "Plan z oryginalnego przewodnika — DOC 24, wersja 1 z 15.11.2023. Stosuj się do oznaczeń i instrukcji na miejscu. Napisy na planie są po francusku.", planTitle: "Plan zakładu", planVersion: "DOC 24 · wersja 1 z 15.11.2023 — plan z oryginalnego przewodnika", planOpen: "Otwórz obraz w nowej karcie", planClose: "Zamknij plan" },
    contacts: { title: "Kto może Ci pomóc?", roles: ["Kierownictwo", "Kierowniczka zakładu i ds. bezpieczeństwa", "Kierownik sadu", "Księgowość", "Osoba przeszkolona w udzielaniu pierwszej pomocy", "Kierownik ds. jakości i pakowania"], emailTitle: "Kontakt z kierownictwem" },
    hours: { title: "Godziny i przerwy.", limits: "Poniższe przedziały oznaczają maksymalny możliwy zakres godzin. Nie są to stałe godziny pracy: obowiązuje grafik przekazany przez przełożonych.", weekdays: "Od poniedziałku do piątku", saturday: "Sobota", breakTitle: "W pokoju przerw", rules: ["Zdejmij fartuch przed wejściem.", "Po skorzystaniu posprzątaj swoje miejsce i używany sprzęt.", "Przed powrotem załóż fartuch i umyj ręce."], apples: "Podczas przerw możesz częstować się jabłkami. Podziel się opinią o ich smaku, konsystencji i jakości." },
    hygiene: { title: "Czysta odzież. Właściwe nawyki.", imageAlt: "Czysta odzież robocza i zakryte włosy", rules: ["Noś czysty, kompletny i zapięty fartuch.", "Całkowicie zakryj włosy czepkiem.", "Noś czyste, zakryte obuwie odpowiednie do stanowiska.", "Miej krótkie paznokcie, bez lakieru i sztucznych paznokci.", "Nie noś biżuterii, z wyjątkiem prostej obrączki; nie noś zegarka ani bransoletek.", "Nie noś widocznego piercingu. Unikaj mocnego makijażu i intensywnych perfum.", "Telefon i rzeczy osobiste trzymaj w wyznaczonym miejscu."], washLead: "Pierze fartuch co najmniej raz w tygodniu w temperaturze 60°C.", washSoon: "Wypierz go wcześniej, jeśli jest brudny lub zabrudzony.", handsTitle: "Mycie rąk", hands: "Myj ręce przy wejściu do strefy produkcji, po każdej przerwie i przed kontaktem z owocami. Umyj je ponownie po skorzystaniu z toalety, wytarciu nosa lub kontakcie z odpadami.", linkClothes: "Przypomnij sobie zasady dotyczące odzieży", linkHands: "Naucz się prawidłowo myć ręce" },
    safety: { title: "Bezpieczeństwo na stanowisku.", imageAlt: "Ilustracja zasad poruszania się po zakładzie", rules: ["Korzystaj z wyznaczonych przejść dla pieszych i przestrzegaj oznaczeń na podłodze.", "Nigdy nie wchodź na trasę pojazdu lub wózka.", "Nie zdejmuj osłon z maszyn.", "Jeśli coś się zablokuje, przerwij pracę i poinformuj przełożonego.", "Niezwłocznie zgłaszaj wypadki i niebezpieczne sytuacje."], emergencyTitle: "W nagłym wypadku", alert: "Powiadom przełożonego lub Dinę, osobę przeszkoloną w udzielaniu pierwszej pomocy. Numer alarmowy:", evacuation: "Po usłyszeniu alarmu natychmiast opuść budynek, nie zabieraj swoich rzeczy i udaj się do miejsca zbiórki na parkingu dla gości.", linkSafety: "Przypomnij sobie zasady bezpieczeństwa", linkEmergency: "Poznaj zasady alarmowania" },
    packing: { title: "Przy pakowaniu liczy się każdy gest.", rules: ["Ostrożnie obchodź się z owocami i przestrzegaj zasad sortowania.", "Używaj tylko wyposażenia dostarczonego przez Pomembal.", "Nigdy nie odkładaj do obiegu owocu, który spadł na podłogę.", "Zgłaszaj brudne opakowanie, zagubiony lub uszkodzony przedmiot, szkło, twardy plastik i wszelkie ciała obce.", "Powiadom przełożonego o błędnej etykiecie, odmianie, kalibrze lub opakowaniu."], motto: "Widzę problem. Działam, jeśli mogę to zrobić bezpiecznie. Zgłaszam.", link: "Przypomnij sobie zasady obchodzenia się z owocami" },
    environment: { title: "Dobre nawyki każdego dnia.", items: [{ title: "Segreguj", text: "Oddzielaj kartony, odpady organiczne i pozostałe odpady zgodnie z zasadami zakładu." }, { title: "Oszczędzaj", text: "Wyłączaj niepotrzebne światło i zakręcaj krany po użyciu." }, { title: "Zgłaszaj", text: "Powiadom przełożonego o marnotrawstwie, wycieku lub usterce." }] },
    team: { title: "Twoje miejsce w zespole.", imageAlt: "Zdjęcie zespołu z oryginalnego przewodnika", picture: "Wspólna chwila zespołu Pomembal.", intro: "Szacunek, etyka i równe traktowanie są częścią życia naszej firmy. Wspólne wydarzenia pomagają nam się lepiej poznać.", rightsTitle: "Twoje prawa i obowiązki", rights: "Przewodnik przypomina o płatnym urlopie, szkoleniach i równym traktowaniu w pracy. O szczegóły dotyczące Twojej sytuacji zapytaj przełożonych.", duties: "Przestrzegaj zasad wewnętrznych, szanuj współpracowników i poufność informacji firmy. Jeśli masz trudności, porozmawiaj z przełożonym." },
    ideas: { title: "Jeden pomysł może coś zmienić.", anonymous: "W pokoju przerw znajduje się skrzynka pomysłów. Możesz anonimowo zaproponować usprawnienie lub zgłosić trudność.", paper: "Organizacja, bezpieczeństwo, jakość, środowisko czy praca w zespole: każda sugestia może pomóc. Zapisz pomysł na kartce bez podawania nazwiska i wrzuć ją do skrzynki.", emailTitle: "Wolisz napisać wiadomość?", email: "Możesz wysłać e-mail do kierownictwa.", emailWarning: "Uwaga: e-mail nie jest anonimowy.", urgent: "W sytuacji pilnej lub niebezpiecznej natychmiast powiadom przełożonego.", emailSubject: "Sugestia dla Pomembal" },
    next: { label: "KOLEJNY ETAP", title: "Poznaj ważne zasady.", intro: "Zapoznaj się z ośmioma tematami szkolenia z higieny i bezpieczeństwa, a następnie sprawdź swoją wiedzę w quizie.", button: "Otwórz szkolenie" },
  },
  PT: {
    chapters: ["Boas-vindas", "A sua chegada", "Contactos", "Horários e pausas", "Vestuário e higiene", "Segurança", "Na embalagem", "Ambiente", "Vida de equipa", "Caixa de ideias"],
    sectionLabels: ["A NOSSA EMPRESA", "O SEU PRIMEIRO DIA", "PESSOAS A CONHECER", "ORGANIZAR O SEU DIA", "HIGIENE DIÁRIA", "PROTEGER-SE E PROTEGER OS OUTROS", "CUIDAR DA FRUTA", "PRESERVAR RECURSOS", "VIVER EM EQUIPA", "A SUA OPINIÃO CONTA"],
    cover: ["POMEMBAL · MANUAL DE ACOLHIMENTO", "Bem-vindo à equipa.", "As pessoas, os locais e os procedimentos que o acompanham desde o primeiro dia.", "Imprimir o manual"],
    nav: ["AS SUAS REFERÊNCIAS", "Índice do manual", "Emergência", "Início do manual"],
    welcome: { title: "A qualidade começa com cada um de nós.", paragraphs: ["A Pomembal embala maçãs para clientes em França e no estrangeiro. Do pomar à embalagem, o cuidado com a fruta orienta o nosso trabalho.", "O respeito pelas pessoas, a qualidade dos produtos e a atenção ao ambiente fazem parte dos nossos compromissos. A sua chegada é uma oportunidade para conhecer os nossos ofícios e a equipa.", "Tem alguma dúvida? Fale com o seu responsável. Terá apoio para conhecer o seu posto de trabalho."], picture: "Do pomar à central.", alt: "Fotografia do pomar do manual de acolhimento original" },
    arrival: { title: "Conheça a central.", parking: "47300 Bias · Existe uma zona reservada ao estacionamento.", intro: "À chegada, apresente-se ao responsável indicado. Peça para lhe mostrarem o seu posto, os vestiários, a sala de pausas, os percursos de circulação e o ponto de encontro.", reminderLabel: "Antes de começar:", reminder: "identifique o seu responsável, o seu horário e posto de trabalho, os vestiários, o vestuário exigido e as instruções de emergência.", planButton: "Ampliar a planta", planAlt: "Planta da central: entrada, escritórios, câmaras frigoríficas, refeitório e instalações sanitárias", planCaption: "Planta do manual original — DOC 24, V1 de 15/11/2023. Siga a sinalização e as instruções no local. Os textos da planta estão em francês.", planTitle: "Planta da central", planVersion: "DOC 24 · V1 de 15/11/2023 — planta do manual original", planOpen: "Abrir a imagem num novo separador", planClose: "Fechar a planta" },
    contacts: { title: "Quem pode ajudá-lo?", roles: ["Direção", "Responsável da central e da segurança", "Responsável do pomar", "Contabilidade", "Socorrista no local de trabalho", "Responsável da qualidade e da embalagem"], emailTitle: "Contactar a direção" },
    hours: { title: "Horários e pausas.", limits: "Os períodos abaixo são os limites máximos possíveis. Não são um horário habitual de trabalho: siga o horário comunicado pela chefia.", weekdays: "Segunda a sexta-feira", saturday: "Sábado", breakTitle: "Na sala de pausas", rules: ["Retire a bata antes de entrar.", "Limpe o seu lugar e os equipamentos depois de os utilizar.", "Volte a vestir a bata e lave as mãos antes de regressar ao trabalho."], apples: "Há maçãs à sua disposição durante as pausas. Gostaríamos de saber a sua opinião sobre o sabor, a textura e a qualidade." },
    hygiene: { title: "Vestuário limpo. Gestos corretos.", imageAlt: "Vestuário de trabalho limpo e cabelo totalmente coberto", rules: ["Use uma bata limpa, completa e fechada.", "Cubra completamente o cabelo com uma touca.", "Use calçado limpo, fechado e adequado ao posto.", "Mantenha as unhas curtas, sem verniz nem unhas artificiais.", "Não use joias, exceto uma aliança simples; não use relógio nem pulseiras.", "Não tenha piercings visíveis. Evite maquilhagem excessiva e perfumes intensos.", "Guarde o telemóvel e os objetos pessoais no local previsto."], washLead: "Lave a bata a 60 °C pelo menos uma vez por semana.", washSoon: "Lave-a mais cedo se estiver suja ou contaminada.", handsTitle: "Lavagem das mãos", hands: "Lave as mãos ao entrar na zona de produção, após cada pausa e antes de tocar na fruta. Volte a lavá-las depois de ir à casa de banho, assoar o nariz ou tocar em resíduos.", linkClothes: "Rever as regras de vestuário", linkHands: "Aprender a lavar as mãos" },
    safety: { title: "Segurança no posto de trabalho.", imageAlt: "Ilustração das regras de circulação na central", rules: ["Respeite os percursos pedonais e as marcações no chão.", "Nunca atravesse a trajetória de um veículo ou empilhador.", "Não retire qualquer proteção das máquinas.", "Em caso de bloqueio, interrompa a tarefa e avise um responsável.", "Comunique imediatamente qualquer incidente ou situação perigosa."], emergencyTitle: "Em caso de emergência", alert: "Avise o responsável ou a Dina, socorrista no local de trabalho. Para contactar os serviços de emergência, ligue:", evacuation: "Quando soar o alarme, saia imediatamente sem recolher os seus pertences e dirija-se ao ponto de encontro no estacionamento de visitantes.", linkSafety: "Rever a segurança na central", linkEmergency: "Conhecer os procedimentos de alerta" },
    packing: { title: "Na embalagem, cada gesto conta.", rules: ["Manuseie a fruta com cuidado e siga as instruções de seleção.", "Utilize apenas o material fornecido pela Pomembal.", "Nunca volte a colocar no circuito uma fruta que tenha caído no chão.", "Comunique qualquer embalagem suja, objeto perdido ou partido, vidro, plástico rígido ou corpo estranho.", "Avise o responsável se houver um erro de rótulo, variedade, calibre ou embalagem."], motto: "Observo. Atuo se o puder fazer em segurança. Aviso.", link: "Rever os cuidados a ter com a fruta" },
    environment: { title: "Gestos úteis, todos os dias.", items: [{ title: "Separar", text: "Separe cartão, resíduos orgânicos e outros resíduos de acordo com as instruções da central." }, { title: "Poupar", text: "Apague as luzes desnecessárias e feche as torneiras após a utilização." }, { title: "Comunicar", text: "Avise o responsável se detetar desperdício, uma fuga ou uma avaria." }] },
    team: { title: "O seu lugar na equipa.", imageAlt: "Fotografia da equipa do manual de acolhimento original", picture: "Um momento partilhado pela equipa Pomembal.", intro: "O respeito, a ética e a igualdade profissional fazem parte da vida da empresa. Os momentos de convívio e os eventos internos também nos ajudam a conhecer-nos melhor.", rightsTitle: "Os seus direitos e deveres", rights: "O manual recorda as férias pagas, a formação e a igualdade profissional. Para conhecer as regras aplicáveis à sua situação, fale com a chefia.", duties: "Respeite as instruções internas, os colegas e a confidencialidade das informações da empresa. Se tiver alguma dificuldade, fale com o seu responsável." },
    ideas: { title: "Uma ideia pode fazer a diferença.", anonymous: "Na sala de pausas, a caixa de ideias permite-lhe sugerir uma melhoria ou comunicar uma dificuldade de forma anónima.", paper: "Organização, segurança, qualidade, ambiente ou vida de equipa: cada sugestão pode melhorar o nosso dia a dia. Escreva a sua ideia numa folha sem indicar o seu nome e coloque-a na caixa.", emailTitle: "Prefere escrever um e-mail?", email: "Também pode enviar uma mensagem à direção.", emailWarning: "Atenção: um e-mail não é anónimo.", urgent: "Se a situação for urgente ou perigosa, avise imediatamente um responsável.", emailSubject: "Sugestão para a Pomembal" },
    next: { label: "A CONTINUAÇÃO DO SEU PERCURSO", title: "Aprenda os bons reflexos.", intro: "Consulte os oito temas da formação sobre Higiene e Segurança e depois ponha os seus conhecimentos à prova no questionário.", button: "Abrir a formação" },
  },
  AR: {
    chapters: ["مرحبًا", "يومك الأول", "جهات الاتصال", "الدوام والاستراحات", "اللباس والنظافة", "السلامة", "في التعبئة", "البيئة", "العمل الجماعي", "صندوق الاقتراحات"],
    sectionLabels: ["شركتنا", "يومك الأول", "أشخاص يمكنك الرجوع إليهم", "تنظيم يوم العمل", "النظافة اليومية", "سلامتك وسلامة الآخرين", "العناية بالفاكهة", "الحفاظ على الموارد", "العمل بروح الفريق", "رأيك مهم"],
    cover: ["POMEMBAL · دليل الترحيب", "مرحبًا بك في الفريق.", "الأشخاص والأماكن والإرشادات التي تساعدك منذ يومك الأول.", "طباعة الدليل"],
    nav: ["معلوماتك الأساسية", "فهرس الدليل", "الطوارئ", "بداية الدليل"],
    welcome: { title: "تبدأ الجودة بمساهمة كل واحد منا.", paragraphs: ["تُعبّئ شركة Pomembal التفاح لعملاء في فرنسا والخارج. ومن البستان إلى التعبئة، توجه العناية بالفاكهة عملنا.", "يشكل احترام الأشخاص وجودة المنتجات والاهتمام بالبيئة جزءًا من التزاماتنا. اغتنم فرصة وصولك للتعرف إلى عملنا وفريقك.", "لديك سؤال؟ اسأل مسؤولك المباشر. ستحصل على المساعدة للتعرف إلى مكان عملك."], picture: "من البستان إلى محطة التعبئة.", alt: "صورة من البستان في الدليل الأصلي" },
    arrival: { title: "تعرّف إلى مكان العمل.", parking: "47300 Bias · توجد مساحة مخصصة لوقوف السيارات.", intro: "عند وصولك، قدّم نفسك للمسؤول المحدد لك. اطلب منه أن يريك مكان عملك وغرف تبديل الملابس وغرفة الاستراحة وممرات التنقل ونقطة التجمع.", reminderLabel: "قبل بدء العمل:", reminder: "تعرّف إلى مسؤولك وساعات عملك ومهمتك ومكان غرف تبديل الملابس واللباس المطلوب وتعليمات الطوارئ.", planButton: "تكبير المخطط", planAlt: "مخطط المحطة: المدخل والمكاتب وغرف التبريد وغرفة الطعام والمرافق الصحية", planCaption: "المخطط مأخوذ من الدليل الأصلي — DOC 24، النسخة 1 بتاريخ 15/11/2023. اتبع اللافتات والتعليمات في الموقع. النصوص المكتوبة على المخطط بالفرنسية.", planTitle: "مخطط المحطة", planVersion: "DOC 24 · النسخة 1 بتاريخ 15/11/2023 — مخطط الدليل الأصلي", planOpen: "فتح الصورة في علامة تبويب جديدة", planClose: "إغلاق المخطط" },
    contacts: { title: "من يمكنه مساعدتك؟", roles: ["الإدارة", "مسؤولة المحطة والسلامة", "مسؤول البستان", "المحاسبة", "المسعفة المعتمدة في مكان العمل", "مسؤول الجودة والتعبئة"], emailTitle: "التواصل مع الإدارة" },
    hours: { title: "ساعات العمل والاستراحات.", limits: "الفترات المذكورة أدناه هي الحدود القصوى الممكنة لأوقات العمل. وهي ليست جدول عمل اعتياديًا؛ اتبع الجدول الذي تُبلّغك به الإدارة.", weekdays: "من الاثنين إلى الجمعة", saturday: "السبت", breakTitle: "في غرفة الاستراحة", rules: ["اخلع معطف العمل قبل الدخول.", "نظّف مكانك والمعدات بعد استخدامها.", "أعد ارتداء معطف العمل واغسل يديك قبل العودة."], apples: "التفاح متاح لك أثناء الاستراحات. نرحب برأيك في مذاقه وقوامه وجودته." },
    hygiene: { title: "لباس نظيف. ممارسات صحيحة.", imageAlt: "لباس عمل نظيف مع تغطية الشعر بالكامل", rules: ["ارتدِ معطف عمل نظيفًا وكاملًا ومغلقًا.", "غطِّ شعرك بالكامل بغطاء الشعر.", "ارتدِ حذاءً نظيفًا ومغلقًا ومناسبًا لمهمتك.", "حافظ على أظافرك قصيرة، من دون طلاء أو أظافر اصطناعية.", "لا ترتدِ الحلي باستثناء خاتم زواج بسيط؛ ولا ساعة أو أساور.", "لا تُظهر أي ثقب للزينة. تجنّب المكياج المبالغ فيه والعطور القوية.", "ضع هاتفك وأغراضك الشخصية في المكان المخصص."], washLead: "اغسل معطف العمل على درجة 60 مئوية مرة واحدة أسبوعيًا على الأقل.", washSoon: "اغسله قبل ذلك إذا اتسخ أو تلوث.", handsTitle: "غسل اليدين", hands: "اغسل يديك عند دخول منطقة الإنتاج، وبعد كل استراحة، وقبل لمس الفاكهة. كرر الغسل بعد استخدام المرحاض أو تمخيط الأنف أو ملامسة النفايات.", linkClothes: "مراجعة قواعد لباس العمل", linkHands: "تعلّم طريقة غسل اليدين" },
    safety: { title: "السلامة في مكان العمل.", imageAlt: "رسم يوضح قواعد التنقل في المحطة", rules: ["التزم بممرات المشاة والعلامات المرسومة على الأرض.", "لا تعبر أبدًا مسار مركبة أو رافعة.", "لا تزل أي حاجز حماية من الآلات.", "عند حدوث انسداد، أوقف ما تقوم به وأبلغ المسؤول.", "أبلغ فورًا عن أي حادث أو وضع خطير."], emergencyTitle: "في حالة الطوارئ", alert: "أبلغ المسؤول أو دينا، المسعفة المعتمدة في مكان العمل. للاتصال بخدمات الطوارئ:", evacuation: "عند سماع الإنذار، أخلِ المكان فورًا من دون أخذ أغراضك، وتوجه إلى نقطة التجمع في موقف سيارات الزوار.", linkSafety: "مراجعة قواعد السلامة في المحطة", linkEmergency: "معرفة كيفية إطلاق الإنذار" },
    packing: { title: "كل حركة مهمة أثناء التعبئة.", rules: ["تعامل مع الفاكهة بعناية واتبع تعليمات الفرز.", "استخدم فقط المعدات التي توفرها Pomembal.", "لا تُعد إلى خط الإنتاج فاكهة سقطت على الأرض.", "أبلغ عن أي عبوة متسخة، أو غرض مفقود أو مكسور، أو زجاج، أو بلاستيك صلب، أو جسم غريب.", "أبلغ المسؤول عند وجود خطأ في الملصق أو الصنف أو الحجم أو العبوة."], motto: "ألاحظ. أتصرف إذا كان ذلك آمنًا. أُبلغ.", link: "مراجعة قواعد التعامل مع الفاكهة" },
    environment: { title: "خطوات مفيدة كل يوم.", items: [{ title: "فرز النفايات", text: "افصل الكرتون والنفايات العضوية عن غيرها وفقًا لتعليمات المحطة." }, { title: "توفير الموارد", text: "أطفئ الأنوار غير اللازمة وأغلق الصنابير بعد الاستخدام." }, { title: "الإبلاغ", text: "أبلغ المسؤول إذا لاحظت هدرًا أو تسربًا أو عطلًا." }] },
    team: { title: "لك مكان في الفريق.", imageAlt: "صورة الفريق من دليل الترحيب الأصلي", picture: "لحظة مشتركة لفريق Pomembal.", intro: "الاحترام والأخلاق والمساواة المهنية جزء من حياتنا في الشركة. وتساعدنا اللقاءات والفعاليات الداخلية أيضًا على التعرف إلى بعضنا.", rightsTitle: "حقوقك وواجباتك", rights: "يذكّر الدليل بالإجازة مدفوعة الأجر والتدريب والمساواة المهنية. اسأل الإدارة عن القواعد التي تنطبق على وضعك.", duties: "احترم التعليمات الداخلية وزملاءك وسرية معلومات الشركة. إذا واجهت صعوبة، فتحدث إلى مسؤولك." },
    ideas: { title: "قد تُحدث فكرة واحدة فرقًا.", anonymous: "يمكنك استخدام صندوق الاقتراحات في غرفة الاستراحة لاقتراح تحسين أو الإبلاغ عن صعوبة بصورة مجهولة الهوية.", paper: "التنظيم والسلامة والجودة والبيئة والعمل الجماعي: قد يساعد كل اقتراح على تحسين عملنا. اكتب فكرتك على ورقة من دون ذكر اسمك، ثم ضعها في الصندوق.", emailTitle: "هل تفضل إرسال رسالة؟", email: "يمكنك إرسال بريد إلكتروني إلى الإدارة.", emailWarning: "تنبيه: البريد الإلكتروني ليس مجهول الهوية.", urgent: "إذا كانت الحالة عاجلة أو خطيرة، فأبلغ المسؤول فورًا.", emailSubject: "اقتراح لشركة Pomembal" },
    next: { label: "الخطوة التالية", title: "تعرّف إلى الممارسات الصحيحة.", intro: "اطلع على الموضوعات الثمانية في تدريب النظافة والسلامة، ثم اختبر معلوماتك.", button: "فتح التدريب" },
  },
};
