import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Bug, FlaskConical, TriangleAlert, ZoomIn } from 'lucide-react';
import type { LanguageCode } from '../content';
import CompanyBrand from '../CompanyBrand';

const titles = ['Pourquoi une démarche HACCP chez Tradipom ?', 'Danger et risque : quelle différence ?', 'Quels dangers pouvons-nous rencontrer ?', 'Et chez Tradipom, comment agit-on ?', 'Concrètement, que fait-on ?', 'Les cinq réflexes essentiels'];
const roles = ['Comprendre les exigences de nos clients', 'Sélectionner et suivre les fournisseurs et prestataires', 'Transmettre les exigences applicables', 'Contrôler les informations et documents nécessaires', 'Assurer la traçabilité', 'Réagir rapidement en cas d’écart'];
const reflexes = [
  ['Connaître les exigences', 'Je m’assure que les exigences du client sont comprises et transmises.'],
  ['Travailler avec des partenaires maîtrisés', 'Les fournisseurs et prestataires doivent être sélectionnés et suivis.'],
  ['Vérifier les informations', 'Les documents, spécifications, certificats et analyses nécessaires doivent être disponibles et cohérents.'],
  ['Assurer la traçabilité', 'Nous devons pouvoir relier rapidement le fournisseur, le produit ou lot et le client.'],
  ['Alerter en cas de doute', 'Ne pas ignorer un écart et ne pas décider seul : transmettre rapidement l’information au Responsable Qualité.'],
];
const situations = [
  { title: 'Résidu de pesticide non conforme', category: 'Danger chimique', text: 'Une analyse révèle un dépassement de la limite applicable sur un lot.', actions: ['Identifier précisément le lot et prévenir rapidement le Responsable Qualité', 'Faire maîtriser ou bloquer le lot si nécessaire', 'Analyser la situation et décider des actions adaptées'], reminder: 'Un produit d’apparence normale peut présenter un danger chimique.' },
  { title: 'Corps étranger signalé par un client', category: 'Danger physique', text: 'Un client signale un corps étranger dans un produit.', actions: ['Recueillir les faits et identifier le produit et le lot', 'Rechercher les autres lots éventuellement concernés', 'Informer le Responsable Qualité et le partenaire concerné', 'Analyser la cause et décider des actions'], reminder: 'Des informations précises permettent de cibler les lots concernés.' },
  { title: 'Alerte sur un produit déjà livré', category: 'Alerte sécurité alimentaire', text: 'Une information indique qu’un produit expédié peut présenter un risque pour la sécurité.', actions: ['Identifier le lot et retrouver le fournisseur et les clients concernés', 'Transmettre rapidement l’alerte au Responsable Qualité', 'Évaluer le risque et bloquer les produits encore disponibles si nécessaire', 'Mettre en œuvre un retrait ou un rappel si la situation le justifie'], reminder: 'La traçabilité permet de retrouver d’où vient le produit et où il a été livré.' },
];
function List({ items }: { items: string[] }) { return <ul>{items.map(item => <li key={item}>{item}</li>)}</ul>; }
function Visual({ src, title }: { src: string; title: string }) {
  return <figure className="haccp-visual"><a href={src} target="_blank" rel="noopener noreferrer" aria-label={`${title} : ouvrir en grand`}><img src={src} alt={title} loading="lazy" /><span><ZoomIn size={20} /> Ouvrir en grand et zoomer</span></a><figcaption>{title}</figcaption></figure>;
}
export default function HaccpTraining({ language, visible, onQuiz, onQuizzes }: { language: LanguageCode; visible: boolean; onQuiz: () => void; onQuizzes: () => void }) {
  const [step, setStep] = useState(0);
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (visible) heading.current?.focus(); }, [visible, step]);
  return <div hidden={!visible}><main className="page-shell haccp-training" dir="ltr" lang="fr">
    <div className="section-heading"><CompanyBrand company="TRADIPOM" /><p className="kicker plain">Formation · 10 à 15 minutes · Consultation libre</p><h1>Maîtrise des dangers et des risques</h1><p>Comprendre l’essentiel de l’HACCP pour maîtriser la sécurité de nos produits.</p></div>
    {language !== 'FR' && <p className="haccp-note">Cette formation est disponible en français pour le moment.</p>}
    <div className="haccp-toolbar"><button className="secondary-button" onClick={onQuizzes}>Retour aux quiz et évaluations</button><button className="secondary-button" onClick={onQuiz}>Passer ou reprendre le quiz HACCP</button></div>
    <nav className="haccp-steps" aria-label="Étapes de la formation">{titles.map((title, i) => <button key={title} aria-current={step === i ? 'step' : undefined} onClick={() => setStep(i)} aria-label={`Étape ${i + 1} : ${title}`}>{i + 1}</button>)}</nav>
    <p className="haccp-position">Étape {step + 1} sur 6</p><div className="quiz-progress" role="progressbar" aria-label="Progression dans la formation" aria-valuemin={1} aria-valuemax={6} aria-valuenow={step + 1}><span style={{ width: `${(step + 1) / 6 * 100}%` }} /></div>
    <section className="haccp-panel"><h2 ref={heading} tabIndex={-1}>{titles[step]}</h2>
      {step === 0 && <><p>Chez Tradipom, nous ne réalisons pas directement toutes les opérations physiques sur les produits. Notre rôle consiste notamment à :</p><List items={roles} /><p>La démarche HACCP permet d’identifier les dangers, d’évaluer les risques et de définir les mesures nécessaires pour les maîtriser.</p><div className="haccp-process">{['Identifier', 'Évaluer', 'Maîtriser', 'Surveiller', 'Améliorer'].map((text, i) => <span key={text}><b>{i + 1}</b>{text}</span>)}</div><p className="haccp-note">Le risque zéro n’existe pas. L’objectif est de prévenir les problèmes et de savoir réagir en cas d’écart. L’HACCP concerne principalement la sécurité alimentaire.</p><Visual src="/images/tradipom-haccp-infographie.webp" title="Infographie HACCP Tradipom : vue d’ensemble" /></>}
      {step === 1 && <><div className="haccp-grid"><article><TriangleAlert /><h3>Danger</h3><p>Un agent ou un élément pouvant nuire à la sécurité du produit.</p><List items={['Une bactérie', 'Un résidu de pesticide', 'Un morceau de verre']} /></article><article><BookOpen /><h3>Risque</h3><p>L’évaluation du danger tient compte notamment de sa <strong>gravité</strong> et de la <strong>probabilité</strong> qu’il survienne.</p></article></div><div className="haccp-process">{['Danger identifié', 'Évaluation du risque', 'Mesures de maîtrise', 'Surveillance et réaction'].map((text, i) => <span key={text}><b>{i + 1}</b>{text}</span>)}</div><p className="haccp-note">On identifie ce qui pourrait poser problème, puis on évalue le risque pour déterminer comment le maîtriser.</p></>}
      {step === 2 && <><div className="haccp-grid"><article><Bug /><h3>Biologiques</h3><List items={['Bactéries', 'Virus', 'Moisissures', 'Parasites']} /></article><article><FlaskConical /><h3>Chimiques</h3><List items={['Résidus de pesticides', 'Contaminants', 'Substances provenant d’un traitement', 'Migration depuis un emballage']} /></article><article><TriangleAlert /><h3>Physiques</h3><List items={['Verre', 'Métal', 'Plastique', 'Bois et pierres', 'Autres corps étrangers']} /></article></div><p className="haccp-note">Les allergènes et certains contaminants émergents sont également pris en compte lorsqu’ils sont pertinents.</p></>}
      {step === 3 && <><p>Tradipom pilote et surveille des opérations réalisées chez les fournisseurs et prestataires.</p><Visual src="/images/tradipom-diagramme-flux.webp" title="Diagramme de flux Tradipom : opérations, traçabilité et gestion des écarts" /><h3>Nos mesures de maîtrise</h3><List items={['Sélection et suivi des fournisseurs et prestataires', 'Transmission des exigences clients', 'Contrôle des documents, spécifications, certificats et analyses nécessaires', 'Traçabilité des lots sur tout le flux', 'Suivi des opérations externalisées', 'Gestion rapide des écarts et réclamations']} /><p className="haccp-note">Même lorsqu’une opération est réalisée chez un partenaire, Tradipom doit s’assurer qu’elle est correctement maîtrisée.</p></>}
      {step === 4 && <div className="haccp-situations">{situations.map((item, i) => <article key={item.title}><p className="kicker plain">Situation {i + 1} · {item.category}</p><h3>{item.title}</h3><p>{item.text}</p><h4>Les bons réflexes</h4><List items={item.actions} /><p className="haccp-note">{item.reminder}</p></article>)}</div>}
      {step === 5 && <><div className="haccp-reflexes">{reflexes.map(([title, text], i) => <article key={title}><span>{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><p className="haccp-note">Le système HACCP est revu au moins une fois par an et avant tout changement susceptible d’avoir un impact sur la sécurité alimentaire.</p><div className="haccp-finish"><h3>Vous avez parcouru la formation</h3><p>À retenir : prévention, traçabilité, surveillance des partenaires et réaction rapide en cas d’écart.</p><p>Le manuel HACCP complet reste le document de référence dans la documentation qualité.</p><button className="primary-button" onClick={onQuiz}>Passer ou reprendre le quiz HACCP <ArrowRight size={20} /></button></div></>}
    </section>
    <div className="haccp-toolbar haccp-navigation"><button className="secondary-button" disabled={step === 0} onClick={() => setStep(i => i - 1)}><ArrowLeft size={20} /> Précédent</button>{step < 5 ? <button className="primary-button" onClick={() => setStep(i => i + 1)}>Suivant <ArrowRight size={20} /></button> : <button className="secondary-button" onClick={() => setStep(0)}>Revoir la formation</button>}</div>
  </main></div>;
}
