import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ClipboardCheck, Clock, FileText, PackageSearch, ShieldAlert, Users } from 'lucide-react';
import type { LanguageCode } from '../content';
import CompanyBrand from '../CompanyBrand';

const titles = ['Pourquoi retrouver un lot rapidement ?', 'Comment identifier un lot ?', 'Quelles informations vérifier ?', 'Une alerte arrive : qui fait quoi ?', 'Retrait ou rappel : quelle différence ?', 'Tester, conserver et améliorer'];
function List({ items }: { items: string[] }) { return <ul>{items.map(item => <li key={item}>{item}</li>)}</ul>; }
function Chain() { return <ol className="traceability-chain"><li><PackageSearch /><strong>Fournisseur / station</strong><span>D’où vient le produit ?</span></li><li><FileText /><strong>Produit et lot</strong><span>Quel produit et quelles quantités ?</span></li><li><Users /><strong>Client</strong><span>À qui a-t-il été livré ?</span></li></ol>; }
export default function TraceabilityTraining({ language, visible, onQuiz, onQuizzes }: { language: LanguageCode; visible: boolean; onQuiz: () => void; onQuizzes: () => void }) {
  const [step, setStep] = useState(0);
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (visible) heading.current?.focus(); }, [visible, step]);
  return <div hidden={!visible}><main className="page-shell haccp-training traceability-training" dir="ltr" lang="fr">
    <div className="section-heading"><CompanyBrand company="TRADIPOM" /><p className="kicker plain">Module 02 · Formation · 10 à 15 minutes · Consultation libre</p><h1>Sécurité des aliments — Traçabilité et gestion d’une alerte</h1><p>Retrouver les produits concernés et réagir rapidement dans l’activité de négoce de Tradipom.</p></div>
    {language !== 'FR' && <p className="haccp-note">Cette formation est disponible en français pour le moment.</p>}
    <div className="haccp-toolbar"><button className="secondary-button" onClick={onQuizzes}>Retour aux formations et évaluations</button><button className="secondary-button" onClick={onQuiz}>Passer ou reprendre le quiz Traçabilité</button></div>
    <nav className="haccp-steps" aria-label="Étapes de la formation Traçabilité">{titles.map((title, i) => <button key={title} aria-current={step === i ? 'step' : undefined} onClick={() => setStep(i)} aria-label={`Étape ${i + 1} : ${title}`}>{i + 1}</button>)}</nav>
    <p className="haccp-position">Étape {step + 1} sur 6</p><div className="quiz-progress" role="progressbar" aria-label="Progression dans la formation Traçabilité" aria-valuemin={1} aria-valuemax={6} aria-valuenow={step + 1}><span style={{ width: `${(step + 1) / 6 * 100}%` }} /></div>
    <section className="haccp-panel"><h2 ref={heading} tabIndex={-1}>{titles[step]}</h2>
      {step === 0 && <><p>La traçabilité permet de savoir d’où vient un produit et à quels clients il a été livré. En cas d’anomalie, elle permet d’identifier les produits concernés pour organiser les actions nécessaires.</p><Chain /><p>Chez Tradipom, elle couvre les achats, les informations sur les lots, la commercialisation et la livraison aux clients.</p><p className="haccp-note"><strong>À retenir :</strong> retrouver le fournisseur, le produit ou lot et les clients destinataires, avec les quantités correspondantes.</p></>}
      {step === 1 && <><div className="haccp-grid"><article><PackageSearch /><h3>Le numéro de lot</h3><p>Il est fourni par le fournisseur ou la station de conditionnement et figure sur l’étiquette de normalisation des colis.</p></article><article><Clock /><h3>Le code d’expédition</h3><p>La procédure prévoit une date codée : une lettre pour le mois et deux chiffres pour le jour.</p><p><strong>Exemple de la procédure : L19 = 19 décembre.</strong></p></article></div><div className="traceability-document"><FileText /><div><h3>Sur le BL ou un document associé</h3><p>Le numéro de lot fournisseur doit figurer sur le bon de livraison (BL) fournisseur ou sur un document associé reliant sans ambiguïté les lots, les quantités et la livraison.</p></div></div><p className="haccp-note">Le rapprochement avec le BL Tradipom permet d’identifier les clients destinataires. Utiliser les identifiants transmis par la station et les documents correspondants.</p><p className="traceability-source">Référence : 4-PRO 01 V1, § 6.1 et 6.4.</p></>}
      {step === 2 && <><p>Le service commercial / achats maintient le système de traçabilité, vérifie les informations fournisseurs et leur transmission aux clients.</p><div className="haccp-process">{['Commande client', 'BL fournisseur', 'BL client'].map((text, i) => <span key={text}><b>{i + 1}</b>{text}</span>)}</div><p>Rapprocher ces trois documents pour vérifier la cohérence des informations. Les commandes et livraisons sont enregistrées dans le système de gestion commerciale existant.</p><h3>Pour un lot, pouvoir retrouver</h3><List items={['Le fournisseur et la station concernés', 'Les documents d’achat associés', 'Les clients ayant reçu ce lot', 'Les quantités correspondantes, pour établir le bilan matière']} /><p className="haccp-note">La chaîne documentaire relie la commande client, la commande station, le BL fournisseur, le BL client et la facture client.</p><p className="traceability-source">Référence : 4-PRO 01 V1, § 3, 6.3, 6.4 et 6.5.</p></>}
      {step === 3 && <><div className="traceability-scenario"><ShieldAlert /><div><h3>« Un client ou une station signale un problème sur un lot. »</h3><p>Recueillir les faits et l’identification du produit, puis transmettre rapidement l’information au Responsable Qualité et à la Direction.</p></div></div><p>La cellule de crise rassemble la Direction, le Responsable Qualité et le service commercial.</p><div className="haccp-grid"><article><Users /><h3>Direction</h3><p>Évalue la situation avec le Responsable Qualité, décide du retrait ou du rappel et valide les décisions importantes et la communication externe.</p></article><article><ShieldAlert /><h3>Responsable Qualité</h3><p>Coordonne, évalue le risque, rassemble la traçabilité, centralise les informations et vérifie l’efficacité des actions et le bilan final.</p></article><article><ClipboardCheck /><h3>Service commercial</h3><p>Identifie les clients concernés, les informe immédiatement dans le cadre du dispositif décidé et suit les réponses et les quantités.</p></article></div><p className="haccp-note">L’analyse porte sur la nature du risque, le produit, les lots, les quantités, les clients et la présence éventuelle du produit chez le consommateur.</p><p className="traceability-source">Référence : 4-PRO 05 V1, § 4, 6.1 et 6.2.</p></>}
      {step === 4 && <><div className="haccp-grid"><article><PackageSearch /><h3>Retrait</h3><p>Empêcher la distribution ou la mise à disposition d’un produit non conforme encore présent dans la <strong>chaîne professionnelle</strong>.</p></article><article><Users /><h3>Rappel</h3><p>Récupérer un produit non conforme susceptible d’avoir déjà atteint le <strong>consommateur</strong>.</p></article></div><h3>Selon la décision prise</h3><List items={['Bloquer les produits encore disponibles', 'Informer immédiatement les clients concernés et informer le fournisseur ou la station', 'Organiser le retour, le blocage ou la destruction des produits', 'Suivre les quantités jusqu’à la clôture de l’incident']} /><h3>Conserver les preuves</h3><p>Les communications précisent le produit, les lots, le motif, les quantités et les actions demandées au client. Conserver les e-mails, accusés de réception et comptes rendus d’appel.</p><p className="haccp-note">Enregistrer les heures de détection de l’incident et de déclenchement de la procédure. Vérifier la cohérence des quantités livrées, disponibles, bloquées, retournées ou détruites.</p><p className="traceability-source">Référence : 4-PRO 05 V1, § 3 et 6.3 à 6.6.</p></>}
      {step === 5 && <><div className="haccp-grid"><article><Clock /><h3>Test de traçabilité</h3><p>Au moins une fois par an et après chaque modification significative du système.</p><p>Retrouver le fournisseur, les documents d’achat, les clients et les quantités d’un lot commercialisé.</p><p><strong>Reconstitution : quatre heures maximum.</strong></p></article><article><ClipboardCheck /><h3>Test de retrait / rappel</h3><p>Au moins une fois par an, enregistré sur <strong>4-ENR 03</strong>.</p><p>Vérifier la traçabilité, les clients, les quantités, les contacts, la rapidité de réaction et l’efficacité du dispositif. Enregistrer les heures de début et de fin.</p></article></div><p className="haccp-note"><strong>Quatre heures est le délai maximal de reconstitution de la traçabilité, pas un délai pour attendre avant de transmettre une alerte.</strong></p><h3>Archiver et améliorer</h3><List items={['Documents commerciaux : au moins cinq ans', 'Documents qualité : au moins deux ans, ou selon les exigences clients', 'Archivage papier ou numérique dans le système documentaire', 'En cas de faiblesse : analyser la cause, définir les actions avec un responsable et un délai, puis vérifier leur efficacité']} /><div className="haccp-finish"><h3>Les réflexes à retenir</h3><p>Identifier le lot, vérifier les documents, retrouver les clients et les quantités, alerter rapidement et conserver les preuves.</p><p>Le quiz évalue la traçabilité et sa contribution à la gestion d’une alerte. Il ne remplace pas le test pratique de retrait/rappel.</p><button className="primary-button" onClick={onQuiz}>Passer ou reprendre le quiz Traçabilité <ArrowRight size={20} /></button></div><p className="traceability-source">Références : 4-PRO 01 V1, § 6.5 à 6.7 ; 4-PRO 05 V1, § 6.7 et 6.8.</p></>}
    </section>
    <div className="haccp-toolbar haccp-navigation"><button className="secondary-button" disabled={step === 0} onClick={() => setStep(i => i - 1)}><ArrowLeft size={20} /> Précédent</button>{step < 5 ? <button className="primary-button" onClick={() => setStep(i => i + 1)}>Suivant <ArrowRight size={20} /></button> : <button className="secondary-button" onClick={() => setStep(0)}>Revoir la formation</button>}</div>
    <p className="traceability-source">Support fondé sur 4-PRO 01 — Traçabilité V1 et 4-PRO 05 — Retrait / Rappel Produit V1. Les procédures applicables restent les documents de référence.</p>
  </main></div>;
}
