import { useEffect, useRef, useState } from "react";
import { ArrowRight, ChevronUp, Expand, GraduationCap, Lightbulb, MapPin, Phone, Printer, X } from "lucide-react";
import type { ThemeId } from "./content";

const chapters = [
  ["bienvenue", "Bienvenue"], ["arrivee", "Votre arrivée"], ["contacts", "Vos contacts"],
  ["horaires", "Horaires & pauses"], ["tenue", "Tenue & hygiène"], ["securite", "Sécurité"],
  ["emballage", "À l’emballage"], ["environnement", "Environnement"], ["collectif", "Vie d’équipe"], ["idees", "Boîte à idées"],
];
const contacts = [
  ["Direction", "Vincent et Sandrine Carrère-Loustaunau"],
  ["Responsable de station et sécurité", "Dina"], ["Responsable verger", "Romain"],
  ["Comptabilité", "Laetitia"], ["Sauveteur secouriste du travail", "Dina"],
  ["Responsable qualité et emballage", "Xavier"],
];
const steps = ["Je sais à qui me présenter.", "Je connais mes horaires et mon poste.", "J’ai repéré les vestiaires et les espaces de pause.", "Je connais la tenue demandée.", "J’ai identifié les consignes d’urgence."];
const STORAGE = "pomembal.arrival.v1";

export default function Booklet({ onTraining, onTheme }: { onTraining: () => void; onTheme: (id: ThemeId) => void }) {
  const [checked, setChecked] = useState<number[]>(() => { try { const value: unknown = JSON.parse(localStorage.getItem(STORAGE) || "[]"); return Array.isArray(value) ? value.filter((n): n is number => Number.isInteger(n) && n >= 0 && n < steps.length) : []; } catch { return []; } });
  const [active, setActive] = useState("bienvenue");
  const [printIdea, setPrintIdea] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  const planButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { try { localStorage.setItem(STORAGE, JSON.stringify(checked)); } catch { /* optional */ } }, [checked]);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { const visible = entries.filter(e => e.isIntersecting).sort((a,b) => a.boundingClientRect.top - b.boundingClientRect.top); if (visible[0]) setActive(visible[0].target.id); }, { rootMargin: "-90px 0px -55% 0px" });
    document.querySelectorAll(".handbook-section").forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, []);
  useEffect(() => { const done = () => setPrintIdea(false); window.addEventListener("afterprint", done); return () => window.removeEventListener("afterprint", done); }, []);
  useEffect(() => { if (printIdea) { const frame = requestAnimationFrame(() => window.print()); return () => cancelAnimationFrame(frame); } }, [printIdea]);
  const trainingLink = (id: ThemeId, label: string) => <button className="handbook-training-link" onClick={() => onTheme(id)}><GraduationCap size={18} />{label}<ArrowRight size={17} /></button>;
  return <main id="main-content" tabIndex={-1} className={`handbook ${printIdea ? "print-idea-only" : ""}`} lang="fr" dir="ltr">
    <header className="handbook-cover"><img src="/images/site-pomembal.webp" alt="Le site Pomembal et les vergers" /><div><p className="welcome-overline">POMEMBAL · VOTRE LIVRET D’ACCUEIL</p><h1>Bienvenue<br />dans l’équipe.</h1><p>Les personnes, les lieux et les gestes qui vous accompagnent dès le premier jour.</p><button className="handbook-print" onClick={() => { setPrintIdea(false); window.print(); }}><Printer size={17} /> Imprimer le livret</button></div></header>
    <div className="handbook-layout"><aside className="handbook-sidebar"><p>VOS REPÈRES</p><nav aria-label="Sommaire du livret">{chapters.map(([id,label],i) => <a href={`#${id}`} key={id} aria-current={active === id ? "location" : undefined}><span>{String(i+1).padStart(2,"0")}</span>{label}</a>)}</nav><a className="handbook-help" href="tel:112"><Phone size={18} /><span>Urgence<strong>112</strong></span></a></aside>
    <div className="handbook-body">
      <section className="handbook-section" id="bienvenue"><span className="chapter-number">01 — NOTRE ENTREPRISE</span><h2>La qualité commence<br />avec chacun de nous.</h2><div className="handbook-editorial"><div><p>Pomembal conditionne des pommes destinées à des clients en France et à l’étranger. Du verger à l’emballage, le soin apporté au fruit guide notre travail.</p><p>Respect des personnes, qualité des produits et attention à l’environnement font partie de nos engagements. Votre arrivée est l’occasion de découvrir nos métiers et de prendre vos repères avec l’équipe.</p><p><strong>Une question ? Demandez à votre responsable.</strong> Vous êtes accompagné dans la découverte de votre poste.</p></div><figure><img src="/images/verger-pomembal.webp" alt="Photographie au verger issue du livret d’accueil" loading="lazy" /><figcaption>Du verger à la station.</figcaption></figure></div></section>
      <section className="handbook-section" id="arrivee"><span className="chapter-number">02 — VOTRE PREMIER JOUR</span><h2>Prendre vos repères.</h2><div className="arrival-address"><MapPin size={24} /><div><strong>1270–1274 route de Lalandette</strong><span>47300 Bias · Un espace est réservé au stationnement.</span></div></div><p>À votre arrivée, présentez-vous au responsable indiqué. Faites-vous montrer votre poste, les vestiaires, la salle de pause, les cheminements et le point de rassemblement.</p><div className="arrival-checklist"><div className="checklist-heading"><h3>Mes repères pour démarrer</h3><span>{checked.length}/{steps.length}</span></div>{steps.map((label,i) => <label key={label}><input type="checkbox" checked={checked.includes(i)} onChange={() => setChecked(prev => prev.includes(i) ? prev.filter(n => n !== i) : [...prev,i])} /><span>{label}</span></label>)}<p>Liste personnelle mémorisée sur cet appareil. Elle ne constitue pas une validation de formation.</p></div><figure className="handbook-plan"><button ref={planButton} onClick={() => dialog.current?.showModal()} aria-label="Agrandir le plan de la station"><img src="/images/plan-station.webp" alt="Plan de la station : SAS d’entrée, bureaux, chambres froides, réfectoire et sanitaires" loading="lazy" /><span><Expand size={17} /> Agrandir le plan</span></button><figcaption>Plan présent dans le livret d’origine — DOC 24, V1 du 15/11/2023. Suivez les affichages et les consignes sur place.</figcaption></figure></section>
      <section className="handbook-section" id="contacts"><span className="chapter-number">03 — LES PERSONNES À CONNAÎTRE</span><h2>Qui peut vous aider ?</h2><dl className="handbook-contacts">{contacts.map(([role,name]) => <div key={role}><dt>{role}</dt><dd>{name}</dd></div>)}</dl><p className="handbook-contact-email">Direction : <a href="mailto:tradipom@gmail.com">tradipom@gmail.com</a><br /><a href="mailto:sandrine.tradipom@gmail.com">sandrine.tradipom@gmail.com</a></p></section>
      <section className="handbook-section" id="horaires"><span className="chapter-number">04 — ORGANISER SA JOURNÉE</span><h2>Horaires et pauses.</h2><p>Les plages ci-dessous sont les <strong>amplitudes maximales possibles</strong>. Elles ne représentent pas un horaire de travail systématique : suivez le planning communiqué par l’encadrement.</p><div className="handbook-hours"><div><span>Lundi au vendredi</span><strong>7 h 50 – 12 h</strong><strong>13 h – 18 h</strong></div><div><span>Samedi</span><strong>7 h 50 – 12 h</strong></div></div><h3>En salle de repos</h3><ul><li>Retirez votre blouse avant d’entrer.</li><li>Nettoyez votre place et les équipements après utilisation.</li><li>Remettez votre blouse et lavez-vous les mains avant la reprise.</li></ul><p>Des pommes sont à votre disposition pendant les pauses. Vos retours sur leur goût, leur texture et leur qualité sont les bienvenus.</p></section>
      <section className="handbook-section" id="tenue"><span className="chapter-number">05 — HYGIÈNE AU QUOTIDIEN</span><h2>Une tenue propre.<br />Les bons gestes.</h2><div className="handbook-visual-row"><img src="/images/tenue.webp" alt="Tenue de travail propre avec cheveux couverts" loading="lazy" /><div><ul><li>Blouse propre, complète et fermée.</li><li>Cheveux entièrement couverts par une charlotte.</li><li>Chaussures propres, fermées et adaptées au poste.</li><li>Ongles courts, sans vernis ni faux ongles.</li><li>Aucun bijou, sauf une alliance simple ; aucune montre ni bracelet.</li><li>Pas de piercing apparent. Évitez maquillage excessif et parfums trop marqués.</li><li>Téléphone et effets personnels rangés dans l’espace prévu.</li></ul></div></div><div className="handbook-key-rule"><span>60 °C</span><p><strong>Blouse lavée au minimum une fois par semaine.</strong><br />Lavez-la plus rapidement si elle est sale ou souillée.</p></div><h3>Le lavage des mains</h3><p>Lavez-vous les mains à l’entrée en production, à chaque reprise et avant tout contact avec les fruits. Renouvelez le lavage après les toilettes, un mouchage ou un contact avec des déchets.</p>{trainingLink("entree", "Revoir les règles de tenue")}{trainingLink("mains", "Apprendre le lavage des mains")}</section>
      <section className="handbook-section" id="securite"><span className="chapter-number">06 — SE PROTÉGER ET PROTÉGER LES AUTRES</span><h2>La sécurité au poste.</h2><div className="handbook-visual-row"><img src="/images/circulation.webp" alt="Illustration des règles de circulation dans la station" loading="lazy" /><div><ul><li>Respectez les cheminements piétons et les marquages au sol.</li><li>Ne traversez jamais la trajectoire d’un engin.</li><li>Ne retirez aucune protection de machine.</li><li>En cas de blocage, arrêtez votre action et prévenez un responsable.</li><li>Signalez immédiatement un incident ou une situation dangereuse.</li></ul></div></div><div className="handbook-emergency"><Phone size={26} /><div><h3>En cas d’urgence</h3><p>Alertez le responsable ou Dina, sauveteur secouriste du travail. Pour joindre les secours : <a href="tel:112">112</a>.</p><p>À l’alarme, évacuez immédiatement, sans récupérer vos affaires, vers le <strong>point de rassemblement au parking visiteurs</strong>.</p></div></div>{trainingLink("securite", "Revoir la sécurité en station")}{trainingLink("urgence", "Connaître les gestes d’alerte")}</section>
      <section className="handbook-section" id="emballage"><span className="chapter-number">07 — LE SOIN APPORTÉ AU FRUIT</span><h2>À l’emballage,<br />chaque geste compte.</h2><ul><li>Manipulez les fruits avec soin et respectez les consignes de tri.</li><li>Utilisez uniquement le matériel fourni par Pomembal.</li><li>Ne remettez jamais dans le circuit un fruit tombé au sol.</li><li>Signalez un emballage sale, un objet perdu ou cassé, du verre, du plastique dur ou un corps étranger.</li><li>Prévenez le responsable en cas d’erreur d’étiquette, de variété, de calibre ou d’emballage.</li></ul><p className="handbook-motto">Je vois. J’agis si je peux le faire sans danger. J’alerte.</p>{trainingLink("fruits", "Revoir les bons gestes avec les fruits")}</section>
      <section className="handbook-section" id="environnement"><span className="chapter-number">08 — PRÉSERVER NOS RESSOURCES</span><h2>Les gestes utiles,<br />tous les jours.</h2><div className="eco-grid"><div><span>01</span><h3>Trier</h3><p>Séparez cartons, déchets organiques et autres déchets selon les consignes de la station.</p></div><div><span>02</span><h3>Économiser</h3><p>Éteignez les lumières inutilisées et fermez les robinets après usage.</p></div><div><span>03</span><h3>Signaler</h3><p>Prévenez le responsable si vous constatez un gaspillage, une fuite ou un dysfonctionnement.</p></div></div></section>
      <section className="handbook-section" id="collectif"><span className="chapter-number">09 — BIEN VIVRE ENSEMBLE</span><h2>Une place dans l’équipe.</h2><figure className="handbook-team"><img src="/images/equipe-pomembal.webp" alt="L’équipe réunie, photo du livret d’accueil" loading="lazy" /><figcaption>Un moment partagé par l’équipe Pomembal.</figcaption></figure><p>Respect, éthique et égalité professionnelle font partie de la vie dans l’entreprise. Les moments conviviaux et les événements internes sont aussi l’occasion de mieux se connaître.</p><h3>Vos droits et vos devoirs</h3><p>Le livret rappelle les congés payés, la formation et l’égalité professionnelle. Pour connaître les modalités qui s’appliquent à votre situation, adressez-vous à l’encadrement.</p><p>Respectez les consignes internes, vos collègues et la confidentialité des informations de l’entreprise. Si vous rencontrez une difficulté, parlez-en à votre responsable.</p></section>
      <section className="handbook-section handbook-ideas" id="idees"><Lightbulb size={35} /><span className="chapter-number">10 — VOTRE AVIS COMPTE</span><h2>Une idée peut<br />faire avancer les choses.</h2><p>Dans la salle de pause, la <strong>boîte à idées</strong> vous permet de proposer une amélioration ou de signaler une difficulté, <strong>de manière anonyme</strong>.</p><p>Organisation, sécurité, qualité, environnement ou vie d’équipe : chaque suggestion peut améliorer notre quotidien. Écrivez avec vos mots, sans indiquer votre nom, et déposez votre papier dans la boîte.</p><p>Vous pouvez aussi en parler directement à un responsable. Pour une situation urgente ou dangereuse, alertez-le immédiatement.</p><button className="handbook-print" onClick={() => setPrintIdea(true)}><Printer size={17} /> Imprimer une fiche à idées</button></section>
      <section className="handbook-next"><GraduationCap size={32} /><div><span className="chapter-number">LA SUITE DE VOTRE PARCOURS</span><h2>Place aux bons réflexes.</h2><p>Retrouvez les huit thèmes de la formation Hygiène et Sécurité, puis testez vos connaissances avec le quiz.</p><button className="primary-button" onClick={onTraining}>Ouvrir la formation <ArrowRight size={19} /></button></div></section>
      <a href="#main-content" className="handbook-top"><ChevronUp size={17} /> Haut du livret</a>
    </div></div>
    <dialog className="plan-dialog" ref={dialog} onClose={() => planButton.current?.focus()} onClick={e => { if(e.target === e.currentTarget) dialog.current?.close(); }} aria-labelledby="plan-title"><div><h2 id="plan-title">Plan de la station</h2><button onClick={() => dialog.current?.close()} aria-label="Fermer le plan"><X /></button></div><p>DOC 24 · V1 du 15/11/2023 — plan du livret d’origine</p><img src="/images/plan-station.webp" alt="Plan de la station en grand format" /><a href="/images/plan-station.webp" target="_blank" rel="noreferrer">Ouvrir l’image dans un nouvel onglet</a></dialog>
    <section className="idea-print-sheet"><h1>Votre idée pour Pomembal</h1><p>Une suggestion anonyme pour améliorer notre quotidien.</p><h2>Ce que j’ai remarqué</h2><div /><h2>Ce que je propose</h2><div /><p>Déposez cette fiche sans votre nom dans la boîte à idées de la salle de pause. Merci pour votre contribution.</p></section>
  </main>;
}
